### PR TITLE
Adding muon ID MVA

### PR DESCRIPTION
**Pull request by andrea21z**
Adding mvaID.onnx, the ML model which will be used in the muon identification.

### CODE REVIEW

**Comment by slava77** [comment]
please add some details about the file. Is this expected to cover all data/MC, or is this specific to Run3/phase-1 (e.g. would it work for phase-2?).
If it is not generic, some specification is needed in the name.

Is the model really so large that the file takes 50MB?
What is the cost of this model use in memory at run time?

**Comment by sscruz** [comment]
hi @slava77 this is meant to be generic - although we haven't explicitly checked whether it will perform well for Phase-2

Regarding the memory consumption, perhaps @andrea21z can check the memory consumption with igprofile (https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Run_profiler_igprof) or you had something else in mind?

**Comment by jpata** [comment]
+reconstruction
- required for https://github.com/cms-sw/cmssw/pull/36179
- tested in https://github.com/cms-sw/cmssw/pull/36179#issuecomment-1013240395

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge
tested with https://github.com/cms-sw/cmssw/pull/36179

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
