### PR TITLE
 Uploading new MVA weight files (with csv) : (muon POG)

### PR DESCRIPTION
**Pull request by bmahakud**
- Creating new pull request to upload MVA weight files trained 
- The weight files for which training was done with deep flavor had been uploaded and merged few days back in the PR https://github.com/cms-sw/cmsdist/issues/4824
- The previous training was performed using the deep flavor of the closest jet. However it is not straightforward to implement this in cmssw, so we roll back to using csv
- So the other PR #4 will be reverted.

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by slava77** [comment]
@bmahakud 

similar to https://github.com/cms-data/RecoMuon-MuonIdentification/pull/4#issuecomment-481689963
the prefix ```MVA_Legacy_CSV_``` in the file name makes the name unnecessarily long and also does not match the old naming pattern.

Considering the recent revert, please provide a link to some slides shown in the MUO POG which describe the performance with these files.

**Comment by sscruz** [comment]
hi @slava77 
I've just posted them in the muon JIRA:
https://its.cern.ch/jira/browse/CMSMUONS-158

**Comment by slava77** [comment]
+1

@mrodozov 
I think that we can move on to the next step and make a cmsdist PR so that this can be tested with cms-sw/cmssw#26460

**Comment by slava77** [comment]
> I think that we can move on to the next step and make a cmsdist PR so that this can be tested with [cms-sw/cmssw#26460](https://github.com/cms-sw/cmssw/pull/26460)

@mrodozov @smuzaffar @fabiocos 
please clarify if this can be merged and the cmsdist could be created in the next day or so.
Thank you.

**Pull request merged**
