### PR TITLE
Uploading new MVA weight files : (muon POG)

### PR DESCRIPTION
**Pull request by bmahakud**
- The weights for the 2016 and 2017 updated trainings are available.
- Need to update the Weights as per availability of new weight files
- See ticket here : https://its.cern.ch/jira/browse/CMSMUONS-158

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by mrodozov** [comment]
@slava77 ping

**Comment by slava77** [comment]
@bmahakud 
is there a matching CMSSW PR for this data PR?

**Comment by sscruz** [comment]
hi @slava77 
we have just done it here:
https://github.com/cms-sw/cmssw/pull/26413

**Comment by slava77** [comment]
Based on cms-sw/cmssw#26413, the file mu_BDTG_Run2017.weights will not be usable anymore.
Please put on a to-do list to remove that file.

I see that the new files names are fairly long and the old naming pattern isn't really preserved
``` MVA_Legacy_deepFlav_together_mu_2016_BDTG.weights.xml```
I'm not sure what the "Legacy" is in the 2017 context, because there was no nominal legacy processing for 2017 yet.
Please consider reducing the file name and perhaps make it with a similar pattern to the old file, e.g.
```mu_BDTG_Run2017_Legacy.weights.xml```.

Additionally, I see that the new files are a factor of 3 larger than the presently used mu_BDTG_Run2017.weights.xml.
Is is because the trees are larger? or is there something with the new format which may be a bit wasteful.

**Comment by mrodozov** [comment]
@slava77 in case I didn't get that right you mean merge this or no ?

**Comment by slava77** [comment]
> @slava77 in case I didn't get that right you mean merge this or no ?

sorry for not being clear in https://github.com/cms-data/RecoMuon-MuonIdentification/pull/5#issuecomment-483393912, I was making a comment to @sscruz to combine two PRs and address the comments in this one https://github.com/cms-data/RecoMuon-MuonIdentification/pull/4#issuecomment-481689963

**Pull request merged**
