### PR TITLE
ttH MVA training for Run2017 data/MC

### PR DESCRIPTION
**Pull request by drkovalskyi**
New training needed for CMSSW_10_2 integration. See https://its.cern.ch/jira/browse/CMSMUONS-158 for details.

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by slava77** [comment]
+1

this PR introduces a new file to be used for 2018 (and 2017?) workflows.
The file size is slightly larger than a similar one already present (1.9 MB vs 1.4 MB). This is very likely acceptable for running in production.

I think that independent of discussion in https://its.cern.ch/jira/browse/CMSMUONS-158
this will still be needed.

@smuzaffar @mrodozov 
please proceed with merging this and making a PR for cmsdist, which we will test at run time as a next step.
IIUC, currently only 10_2_X version is needed

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
cmsdist PR for 10.2.X is https://github.com/cms-sw/cmsdist/pull/4127

**Comment by drkovalskyi** [comment]
@smuzaffar when can I expect it to become available in nightlies? I don't see the file in CMSSW_10_2_X_2018-06-20-2300 and without it I cannot commit changes that are needed for CMSSW_10_2_X release.

**Comment by slava77** [comment]
On 6/21/18 8:15 AM, drkovalskyi wrote:
> @smuzaffar <https://github.com/smuzaffar> when can I expect it to become
> available in nightlies? I don't see the file in
> CMSSW_10_2_X_2018-06-20-2300 and without it I cannot commit changes that
> are needed for CMSSW_10_2_X release.
> 

we can test PRs with proposed externals without a merge of the external
in the IB.

**Pull request merged**
