### PR TITLE
Adding low pt muon MVA (muon POG)

### PR DESCRIPTION
**Pull request by sscruz**
Muon POG plans to add a new muons MVA targetting low pt muons. Details are being discussed in https://its.cern.ch/jira/browse/CMSMUONS-158. 
PR to include the new selector in cmssw will follow shortly

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by slava77** [comment]
@sscruz 
the same questions as in https://github.com/cms-data/RecoMuon-MuonIdentification/pull/4/#issuecomment-481689963 apply here to the file size:
the new files are a factor of 3 larger than the presently used mu_BDTG_Run2017.weights.xml.
Is is because the trees are larger? or is there something with the new format which may be a bit wasteful.

**Comment by sscruz** [comment]
@slava77 indeed, the new BDT have a bit more trees (800 vs 1000), and each tree is also larger: we allow for a maximum depth of 4 instead of 2 now, and nodes with smaller size are allowed. It is expected that we have larger files then

**Comment by slava77** [comment]
I suggest to merge this with #4 
This way we'll be able to test cms-sw/cmssw#26460 with the standard tools.

**Comment by slava77** [comment]
@mrodozov 

sorry for not being clear in https://github.com/cms-data/RecoMuon-MuonIdentification/pull/5#issuecomment-483393912, I was making a comment to @sscruz asking to combine two PRs and address the comments in this one https://github.com/cms-data/RecoMuon-MuonIdentification/pull/4#issuecomment-481689963

Based on the feedback so far, only the file renaming for the files introduced in #4 is missing.
So, a followup PR can be rather simple.

**Pull request merged**
